import { v4 as uuidv4 } from 'uuid';

export const appointments = [
  {
    title: "Param Kothari",
    profilePicture: "",
    startDate: new Date(),
    endDate: new Date(new Date().getTime() + 1000 * 60 * 60 * 10),
    id: uuidv4(),
    additionalNotes: "",
    illness: "Fever",
    illnessDescription: "",
    medicalHistory: {},
    location: "Room 2",
    age: 15,
    gender: "Male",
    status: "Confirmed",
    mode: "Online",
    meetLink: ""
  },
  {
    title: "Param Kothari",
    profilePicture: "",
    startDate: new Date(),
    endDate: new Date(new Date().getTime() + 1000 * 60 * 60 * 10),
    id: uuidv4(),
    additionalNotes: "",
    illness: "Fever",
    illnessDescription: "",
    medicalHistory: {},
    location: "Room 2",
    age: 15,
    gender: "Male",
    status: "Confirmed",
    mode: "Online",
    meetLink: ""
  },{
    title: "Param Kothari",
    profilePicture: "",
    startDate: new Date(),
    endDate: new Date(new Date().getTime() + 1000 * 60 * 60 * 10),
    id: uuidv4(),
    additionalNotes: "",
    illness: "Fever",
    illnessDescription: "",
    medicalHistory: {},
    location: "Room 2",
    age: 15,
    gender: "Male",
    status: "Confirmed",
    mode: "Online",
    meetLink: ""
  },{
    title: "Param Kothari",
    profilePicture: "",
    startDate: new Date(),
    endDate: new Date(new Date().getTime() + 1000 * 60 * 60 * 10),
    id: uuidv4(),
    additionalNotes: "",
    illness: "Fever",
    illnessDescription: "",
    medicalHistory: {},
    location: "Room 2",
    age: 15,
    gender: "Male",
    status: "Confirmed",
    mode: "Online",
    meetLink: ""
  },{
    title: "Param Kothari",
    profilePicture: "",
    startDate: new Date(),
    endDate: new Date(new Date().getTime() + 1000 * 60 * 60 * 10),
    id: uuidv4(),
    additionalNotes: "",
    illness: "Fever",
    illnessDescription: "",
    medicalHistory: {},
    location: "Room 2",
    age: 15,
    gender: "Male",
    status: "Confirmed",
    mode: "Online",
    meetLink: ""
  },{
    title: "Param Kothari",
    profilePicture: "",
    startDate: new Date(),
    endDate: new Date(new Date().getTime() + 1000 * 60 * 60 * 10),
    id: uuidv4(),
    additionalNotes: "",
    illness: "Fever",
    illnessDescription: "",
    medicalHistory: {},
    location: "Room 2",
    age: 15,
    gender: "Male",
    status: "Confirmed",
    mode: "Online",
    meetLink: ""
  },{
    title: "Param Kothari",
    profilePicture: "",
    startDate: new Date(),
    endDate: new Date(new Date().getTime() + 1000 * 60 * 60 * 10),
    id: uuidv4(),
    additionalNotes: "",
    illness: "Fever",
    illnessDescription: "",
    medicalHistory: {},
    location: "Room 2",
    age: 15,
    gender: "Male",
    status: "Confirmed",
    mode: "Online",
    meetLink: ""
  },{
    title: "Param Kothari",
    profilePicture: "",
    startDate: new Date(),
    endDate: new Date(new Date().getTime() + 1000 * 60 * 60 * 10),
    id: uuidv4(),
    additionalNotes: "",
    illness: "Fever",
    illnessDescription: "",
    medicalHistory: {},
    location: "Room 2",
    age: 15,
    gender: "Male",
    status: "Confirmed",
    mode: "Online",
    meetLink: ""
  },{
    title: "Param Kothari",
    profilePicture: "",
    startDate: new Date(),
    endDate: new Date(new Date().getTime() + 1000 * 60 * 60 * 10),
    id: uuidv4(),
    additionalNotes: "",
    illness: "Fever",
    illnessDescription: "",
    medicalHistory: {},
    location: "Room 2",
    age: 15,
    gender: "Male",
    status: "Confirmed",
    mode: "Online",
    meetLink: ""
  },{
    title: "Param Kothari",
    profilePicture: "",
    startDate: new Date(),
    endDate: new Date(new Date().getTime() + 1000 * 60 * 60 * 10),
    id: uuidv4(),
    additionalNotes: "",
    illness: "Fever",
    illnessDescription: "",
    medicalHistory: {},
    location: "Room 2",
    age: 15,
    gender: "Male",
    status: "Confirmed",
    mode: "Online",
    meetLink: ""
  },{
    title: "Param Kothari",
    profilePicture: "",
    startDate: new Date(),
    endDate: new Date(new Date().getTime() + 1000 * 60 * 60 * 10),
    id: uuidv4(),
    additionalNotes: "",
    illness: "Fever",
    illnessDescription: "",
    medicalHistory: {},
    location: "Room 2",
    age: 15,
    gender: "Male",
    status: "Confirmed",
    mode: "Online",
    meetLink: ""
  },{
    title: "Param Kothari",
    profilePicture: "",
    startDate: new Date(),
    endDate: new Date(new Date().getTime() + 1000 * 60 * 60 * 10),
    id: uuidv4(),
    additionalNotes: "",
    illness: "Fever",
    illnessDescription: "",
    medicalHistory: {},
    location: "Room 2",
    age: 15,
    gender: "Male",
    status: "Confirmed",
    mode: "Online",
    meetLink: ""
  }
];
